version: '3.8'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - challenge

  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest 
    networks:
      - challenge

  test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest 
    networks:
      - challenge

networks:
  challenge:
